### PR TITLE
Fix horizontal alignment and remove title color change

### PR DESCRIPTION
**Pull request by emil-furniss**
This addresses the alignment issue from #3, and by explicit request from design, removes the color change of the title when it expands.

### CODE REVIEW

**Comment by emil-furniss** [comment]
@dbatiste @dlockhart @jwong-d2l Hey there, I was unable to add reviewers in the conventional manner, but a quick review would be appreciated. Thanks!

**Comment by dlockhart** [comment]
I've adjusted the permissions on the repo.

So @margaree has just converted accordion to Polymer 3, hence the merge conflicts. You'll want to adjust this so that it's going into the `hybrid` branch. Then once it merges we'll want to re-convert it to Polymer 3 to pick up the changes.

**Comment by emil-furniss** [comment]
Thanks and sorry for the unfortunate timing, I've adjusted the target and can take care of converting the changes to Polymer 3.

**Comment by dlockhart** [comment]
Thanks @emil-furniss. Hopefully you can just re-run the [toPolymer3.sh script](https://github.com/Brightspace/polymer-3-converter/blob/master/toPolymer3.sh) on the hybrid branch and do a PR into `master`. There doesn't appear to be a patch of any kind required.

**Pull request merged**
